<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello Promise</h1>
    <script>
        let p1 = new Promise((resolve, reject)=>{
    console.log('promise is pending');
    setTimeout(() => {
        // console.log('I am promise and i am fulfill');
        resolve('I am resolved') // for resolve
    }, 3000);
})
        let p2 = new Promise((resolve, reject)=>{
    console.log('promise is pending');
    setTimeout(() => {
        // console.log('I am promise and i am reject');
        reject(new Error('I am an error!')) // for reject
    }, 4000);
})

p1.then((value)=>{
    console.log(value, "in p1");
})
p2.catch((error)=>{
    console.log("Error: occurred in p2" , );   // hamne error ko catch kar liya taki console me error show naa ho. kyuki error ko hamne handle kar liya.
})
// console.log(p1,p2);
    </script>
</body>
</html>